# Path-based labels
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'
      - '.goreleaser.yml'
      - '.golangci.yml'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'examples/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_test.go'

server:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/kompakt/**/*'
      - 'internal/server/**/*'

agent:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/kompakt-agent/**/*'
      - 'internal/agent/**/*'

common:
  - changed-files:
    - any-glob-to-any-file:
      - 'internal/common/**/*'

# Branch-based labels
breaking:
 - head-branch: ['^breaking/', '^major/']

feature:
 - head-branch: ['^feature/', '^feat/', '^enhancement/', '^minor/']

bugfix:
 - head-branch: ['^bugfix/', '^fix/', '^patch/', '^hotfix/']

refactor:
 - head-branch: ['^refactor/', '^rework/', '^cleanup/']

security:
 - head-branch: ['^security/', '^sec/', '^cve/']
