# Path-based labels
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/actions/*'
      - '.github/workflows/*'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/*.md'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*_test.go'

build:
  - changed-files:
    - any-glob-to-any-file:
      - '.goreleaser.yml'
      - '.golangci.yml'
      - '.github/actions/**/*'

daemon:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/kompakt/**/*'
      - 'internal/daemon/**/*'

agent:
  - changed-files:
    - any-glob-to-any-file:
      - 'cmd/kompakt-agent/**/*'
      - 'internal/client/**/*'

common:
  - changed-files:
    - any-glob-to-any-file:
      - 'internal/common/**/*'

# Branch-based labels
breaking:
 - head-branch: ['^breaking', 'breaking', 'major']

feature:
 - head-branch: ['^feature', 'feature', 'enhancement', 'feat', 'add', 'minor']

bugfix:
 - head-branch: ['^bugfix', 'bugfix', 'fix', 'patch', 'hotfix']

