# .github/release.yml
changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking
    - title: 🔒 Security
      labels:
        - security
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bugfixes
      labels:
        - bugfix
    - title: ♻️ Refactoring
      labels:
        - refactor
    - title: 🧪 Tests
      labels:
        - tests
    - title: 🛠️ Build and CI
      labels:
        - ci
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 📚 Documentation
      labels:
        - docs
