version: 2

project_name: kompakt

builds:
  - id: kompakt
    binary: kompakt
    main: ./cmd/kompakt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

  - id: kompakt-agent
    binary: kompakt-agent
    main: ./cmd/kompakt-agent
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: server-archive
    ids:
      - kompakt
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: agent-archive
    ids:
      - kompakt-agent
    name_template: >-
      {{ .ProjectName }}-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
