name: CI
run-name: "${{ github.event.repository.name }} | CI | ${{ github.run_id }} | ${{ github.event_name }}"
permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

  pull_request:
    branches:
      - main
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'cmd/**'
      - 'internal/**'
      - '.github/**/*'
      - 'go.mod'
      - 'go.sum'

jobs:
  labels:
    name: Label Changes
    runs-on: [ubuntu-latest]
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Labeler
      id: labeler
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b #v6.0.1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run golangci-lint
        uses: ./.github/actions/go-lint

  test:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Go Tests
        uses: ./.github/actions/go-test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-version: ${{ steps.build.outputs.release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build binaries
        id: build
        uses: ./.github/actions/go-build
        with:
          release-type: 'debug'
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: debug-binaries-${{ runner.os }}
          path: dist/debug/
          retention-days: 30
          if-no-files-found: warn